### ISSUE TITLE
Grabbing Focus Issues

### ISSUE THREAD

**Issue by Velocikitty** [Wurielle/izabela-desktop#23] opened 2020-02-05 01:53 UTC
Sometimes Iza will grab focus, other times it won't.

Using the newest version.

**Comment by Velocikitty** [comment] 2020-02-05 01:59
Seems it could be related to text boxes that preventing it from stealing focus.

**Comment by Wurielle** [comment] 2020-02-05 16:55
Hello @Velocikitty! 

The issue comes from pressing the `Alt` key within focusable elements. Assuming you're using the default keybinding (`Alt` + `Enter`), pressing `Alt` then `Enter` can make you lose focus for those elements but won't make you lose focus from the window.

I would suggest changing the key binding to something like `Ctrl` + `Space` if that is an issue for you.

**Comment by Velocikitty** [comment] 2020-02-05 20:31
I'll give it a shot, but even if I had a text box selected (Say Twitch Chat), it wouldn't take the focus properly.

**Comment by Wurielle** [comment] 2020-03-08 16:00
I'll close this for now as I cannot reproduce this issue. My guess is exiting overlay mode with `Alt` being the last key pressed removes the focus from focusable elements such as inputs. This can be fixed by changing the key binding for overlay mode.

**Closed by Wurielle** 2020-03-08 16:00 UTC
