### ISSUE TITLE
New key bind doesn't override old key bind

### ISSUE THREAD

**Issue by PleaseDontEatMe** [Wurielle/izabela-desktop#36] opened 2020-03-10 06:59 UTC
The original button to open the thing is 'Alt + Enter'. I changed it to 'Ctrl + up' but even after doing this, the 'Alt + Enter' still stays and I can't find a way to remove the 'Alt + Enter' bind.
![Izabela problem](https://user-images.githubusercontent.com/62006196/76287553-3292a100-62be-11ea-8f98-0a70acda901f.png)

**Comment by Wurielle** [comment] 2020-03-14 07:12
Hello @PleaseDontEatMe! Sorry for the late answer, I didn't see the issue earlier..

Does it still not work even after restarting the application? Are you running on windows 7, 8, 8.1 or 10?

**Comment by Wurielle** [comment] 2020-10-22 14:12
Can't reproduce so I'm closing for now.  Feel free to reopen if it is still happening.

**Closed by Wurielle** 2020-10-22 14:12 UTC
