### ISSUE TITLE
Inconsistent API Voice is back

### ISSUE THREAD

**Issue by ArcAngelica** [Wurielle/izabela-desktop#32] opened 2020-03-05 05:19 UTC
The old problem related to having voices randomly change with sentences is back, that was brought up by [FlufflesTheDog](https://github.com/Wurielle/izabela-desktop/issues/7) a year ago

Though this time thanks to the updates I was able to [record the voices randomly changing](
https://ufile.io/9n0xqea0) in case you're not able to replicate it
_Latest Release, Responsive Voice, UK Female and US Female affected_

Has any solution been found since last time this happened? Is there a workaround?

Its an interesting "bug", I personally love the sound of US Female voice, but I really can't lose UK Female voice for that... Would be nice if there was a way to keep both the original voices and these different weird and obviously buggy voices without them having to completely override one another

**Comment by Nexhin** [comment] 2020-03-05 16:45
I'm having the same "issue," but as someone who almost exclusively uses the UK Female voice, I'm actually quite fond of the new voice. An option or something similar to be able to change between these voices would certainly be a welcome addition. An interesting bug for sure.

**Comment by EvilPasta** [comment] 2020-03-05 18:17
I think those new voices don't work with some words. Anyway, what if new voices were separated from the old ones. Maybe called like "US English Female 2", etc

**Comment by Wurielle** [comment] 2020-03-06 20:41
Hello everyone! Thanks for letting me know about the issue!

Thanks a lot @ArcAngelica for the files, I couldn't reproduce the issue before but thanks to them I managed to find a workaround.

In the meantime if you type `cool.` instead of `cool` it will pronounce it in the correct voice. My workaround will essentially be the same since the issue is not exactly occuring on the software's end but at least it should be more consistent from now on.

Unfortunately I can't provide more voices than the ones already listed unless I made my own API. This is something I want to implement for sure but I need to seriously think it through before making any decisions or promises about it.

**Comment by ArcAngelica** [comment] 2020-03-07 02:29
I'm glad I could help!
Adding a `space` to the end of a word also consistently makes you use the new voices as well.

I do want to emphasize tho that these voices that are currently being used for saying sentences are the _new_ ones, **the old previous voices are considered the "correct ones"**, because althought its up to taste whether the new ones are better, they clearly showed up one day without warning and don't consistently work without workarounds, hence the issue report.

If no middle ground can be met where we get to keep both old and new ones, I'd prefer if we sticked to the old voices which would consider it "fixed".
My opinion is biased tho, cause I personally not only prefer the old UK Female, but all my friends are used to that voice by now, switching tones and voices suddenly can be a tough thing to do when you're already attached for years, and I believe I'm not alone in this.

**Comment by Wurielle** [comment] 2020-03-07 08:39
I understand how you feel but I don't have any control over the voices returned by the API. 

Responsive Voice is kindly free for non-commercial projects and is the best option that could be implemented in such a project as of now. Unfortunately that also means I have to follow their rules and update the software whenever they update their API. 

I simply cannot afford running my own TTS API because of financial and legal concerns. I would really love to keep the software as free as possible because it helps a lot of people with disabilities but I cannot afford to pay for a TTS service on my own for all my users since I'm just one developer developing the software on my free time.

I hope I can find an ultimate solution in a near future but for now this is all I can offer, sorry..

**Comment by Wurielle** [comment] 2020-03-08 11:23
Should be fixed with [v0.10.3](https://github.com/Wurielle/izabela-desktop/releases/tag/v0.10.3). Feel free to reopen if that's still occuring.

**Closed by Wurielle** 2020-03-08 11:23 UTC
Labels: watching

**Comment by Wurielle** [comment] 2020-03-13 19:59
I found a parameter that allows me to change the voice's engine. On some voices the sound is different depending on the engine. I'm not sure if you can get the "old" voices from there but I might as well implement an option to change it and let you experiment with it.

**Comment by ArcAngelica** [comment] 2020-03-14 04:31
Would love to try that if possible! Thanks for digging into this

**Comment by Wurielle** [comment] 2020-03-15 09:09
In [0.11.0](https://github.com/Wurielle/izabela-desktop/releases/tag/v0.11.0) I added the option to change the voice engine. Selecting "2" kinda sounds like the "old" voice I think? By default it used to use the latest engine so I guess there is a way to change the voice.

What I don't know is if it's gonna work forever or if this works with every voices. If a voice isn't working you can select "Auto" just in case so that it tries to choose a default engine. That's the best I can provide regarding this "new" voice vs "old" voice issue. Hope that helps!

![image](https://user-images.githubusercontent.com/15323067/76698482-b3c5ab80-66a3-11ea-93d8-67bb76df7d83.png)
